name:                haskell-data-sink-demo
version:             0.1.0.0
github:              "ketzacoatl/haskell-data-sink-demo"
license:             BSD3
author:              "Ketzacoatl"
maintainer:          "ketzacoatl"
copyright:           "2017 Contributors"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
synopsis:            Demo a basic data sink pipeline in Haskell
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on Github at <https://github.com/ketzacoatl/haskell-data-sink-demo#readme>

dependencies:
  - aeson
  - attoparsec
  - base               >= 4.7 && < 5
  - blaze-builder
  - bytestring
  - conduit
  - conduit-extra
  - http-types
  - lifted-base
  - network
  - wai
  - wai-conduit
  - warp
  - yesod-core
 
library:
  source-dirs: src

executables:
  haskell-data-sink-demo:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - haskell-data-sink-demo

tests:
  haskell-data-sink-demo-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - haskell-data-sink-demo
